steps:
  - name: Checkout
  - uses: actions/checkout@master

  - name: Semantic Releease
  - uses: codfish/semantic-release-action@master
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}